channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.*
  - scipy
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - statsmodels
  - biom-format
  - aiohttp
  - pytest
  - wget
  - pip:
    - matplotlib-venn
    - KEGG-parser
